//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPlato_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESSION
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DOB { get; set; }
        public string PROFESSION1 { get; set; }
    }
}
